## Importing Required Libraries

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

## Using Diabetes Diagonsing Dataset and Loading it.

In [2]:
df = pd.read_csv('data.csv')

## Data Preprocessing

In [3]:
df.isnull()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
111,False,False,False,False,False,False,False,False,False,False
112,False,False,False,False,False,False,False,False,False,False
113,False,False,False,False,False,False,False,False,False,False
114,False,False,False,False,False,False,False,False,False,False
115,False,False,False,False,False,False,False,False,False,False

In [22]:
missing_values = df.isnull().sum().sum()
print(f"Total Missing Values : {missing_values}")

Total Missing Values : 0

In [5]:
print(missing_values)

Age               0
BMI               0
Glucose           0
Insulin           0
HOMA              0
Leptin            0
Adiponectin       0
Resistin          0
MCP.1             0
Classification    0
dtype: int64

In [6]:
df.shape

(116, 10)

In [7]:
df.columns

Index(['Age', 'BMI', 'Glucose', 'Insulin', 'HOMA', 'Leptin', 'Adiponectin',
       'Resistin', 'MCP.1', 'Classification'],
      dtype='object')

In [8]:
df.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,48,23.500000,70,2.707,0.467409,8.8071,9.702400,7.99585,417.114,1
1,83,20.690495,92,3.115,0.706897,8.8438,5.429285,4.06405,468.786,1
2,82,23.124670,91,4.498,1.009651,17.9393,22.432040,9.27715,554.697,1
3,68,21.367521,77,3.226,0.612725,9.8827,7.169560,12.76600,928.220,1
4,86,21.111111,92,3.549,0.805386,6.6994,4.819240,10.57635,773.920,1

In [9]:
df.describe()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1
count,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000
mean,57.301724,27.582111,97.793103,10.012086,2.694988,26.615080,10.180874,14.725966,534.647000
std,16.112766,5.020136,22.525162,10.067768,3.642043,19.183294,6.843341,12.390646,345.912663
min,24.000000,18.370000,60.000000,2.432000,0.467409,4.311000,1.656020,3.210000,45.843000
25%,45.000000,22.973205,85.750000,4.359250,0.917966,12.313675,5.474283,6.881763,269.978250
50%,56.000000,27.662416,92.000000,5.924500,1.380939,20.271000,8.352692,10.827740,471.322500
75%,71.000000,31.241442,102.000000,11.189250,2.857787,37.378300,11.815970,17.755207,700.085000
max,89.000000,38.578759,201.000000,58.460000,25.050342,90.280000,38.040000,82.100000,1698.440000

In [10]:
data_types = df.dtypes
print('Data Types\n',data_types)

Data Types
 Age                 int64
BMI               float64
Glucose             int64
Insulin           float64
HOMA              float64
Leptin            float64
Adiponectin       float64
Resistin          float64
MCP.1             float64
Classification     object
dtype: object

## Data Formatting and Data Normalisation

In [11]:
df['Age'] = df['Age'].astype('float')

In [12]:
df.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,48.0,23.500000,70,2.707,0.467409,8.8071,9.702400,7.99585,417.114,1
1,83.0,20.690495,92,3.115,0.706897,8.8438,5.429285,4.06405,468.786,1
2,82.0,23.124670,91,4.498,1.009651,17.9393,22.432040,9.27715,554.697,1
3,68.0,21.367521,77,3.226,0.612725,9.8827,7.169560,12.76600,928.220,1
4,86.0,21.111111,92,3.549,0.805386,6.6994,4.819240,10.57635,773.920,1

In [13]:
df['Classification'] = df['Classification'].astype('category')

In [14]:
df.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,48.0,23.500000,70,2.707,0.467409,8.8071,9.702400,7.99585,417.114,1
1,83.0,20.690495,92,3.115,0.706897,8.8438,5.429285,4.06405,468.786,1
2,82.0,23.124670,91,4.498,1.009651,17.9393,22.432040,9.27715,554.697,1
3,68.0,21.367521,77,3.226,0.612725,9.8827,7.169560,12.76600,928.220,1
4,86.0,21.111111,92,3.549,0.805386,6.6994,4.819240,10.57635,773.920,1

In [15]:
scaler = MinMaxScaler()

In [16]:
df[['Age', 'BMI', 'Glucose', 'Insulin', 'HOMA', 'Leptin', 'Adiponectin', 'Resistin', 'MCP.1']] = scaler.fit_transform(df[['Age', 'BMI', 'Glucose', 'Insulin', 'HOMA', 'Leptin', 'Adiponectin', 'Resistin', 'MCP.1']])

In [17]:
df.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,0.369231,0.253850,0.070922,0.004908,0.000000,0.052299,0.221152,0.060665,0.224659,1
1,0.907692,0.114826,0.226950,0.012190,0.009742,0.052726,0.103707,0.010826,0.255926,1
2,0.892308,0.235278,0.219858,0.036874,0.022058,0.158526,0.571021,0.076906,0.307912,1
3,0.676923,0.148328,0.120567,0.014171,0.005911,0.064811,0.151538,0.121131,0.533934,1
4,0.953846,0.135640,0.226950,0.019936,0.013748,0.027782,0.086940,0.093375,0.440565,1

## Turn Categorical Variables into Quantitive Variables

In [18]:
encoder = LabelEncoder()

In [19]:
df['Classification'] = encoder.fit_transform(df['Classification'])

In [20]:
df.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,0.369231,0.253850,0.070922,0.004908,0.000000,0.052299,0.221152,0.060665,0.224659,0
1,0.907692,0.114826,0.226950,0.012190,0.009742,0.052726,0.103707,0.010826,0.255926,0
2,0.892308,0.235278,0.219858,0.036874,0.022058,0.158526,0.571021,0.076906,0.307912,0
3,0.676923,0.148328,0.120567,0.014171,0.005911,0.064811,0.151538,0.121131,0.533934,0
4,0.953846,0.135640,0.226950,0.019936,0.013748,0.027782,0.086940,0.093375,0.440565,0

In [21]:
df.groupby('Classification').size()

Classification
0    50
1    64
2     2
dtype: int64